# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import c2_pb2 as c2__pb2


class C2Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartJob = channel.unary_unary(
                '/C2/StartJob',
                request_serializer=c2__pb2.StartJobRequest.SerializeToString,
                response_deserializer=c2__pb2.StartJobResponse.FromString,
                )
        self.GetJob = channel.unary_unary(
                '/C2/GetJob',
                request_serializer=c2__pb2.GetJobRequest.SerializeToString,
                response_deserializer=c2__pb2.Job.FromString,
                )
        self.StopJob = channel.unary_unary(
                '/C2/StopJob',
                request_serializer=c2__pb2.StopJobRequest.SerializeToString,
                response_deserializer=c2__pb2.StopJobResponse.FromString,
                )


class C2Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_C2Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartJob': grpc.unary_unary_rpc_method_handler(
                    servicer.StartJob,
                    request_deserializer=c2__pb2.StartJobRequest.FromString,
                    response_serializer=c2__pb2.StartJobResponse.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=c2__pb2.GetJobRequest.FromString,
                    response_serializer=c2__pb2.Job.SerializeToString,
            ),
            'StopJob': grpc.unary_unary_rpc_method_handler(
                    servicer.StopJob,
                    request_deserializer=c2__pb2.StopJobRequest.FromString,
                    response_serializer=c2__pb2.StopJobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'C2', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class C2(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/C2/StartJob',
            c2__pb2.StartJobRequest.SerializeToString,
            c2__pb2.StartJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/C2/GetJob',
            c2__pb2.GetJobRequest.SerializeToString,
            c2__pb2.Job.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/C2/StopJob',
            c2__pb2.StopJobRequest.SerializeToString,
            c2__pb2.StopJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
