# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: c2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='c2.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08\x63\x32.proto\"4\n\x0fStartJobRequest\x12\x11\n\tcommandId\x18\x01 \x01(\x05\x12\x0e\n\x06userId\x18\x02 \x01(\t\"{\n\x10StartJobResponse\x12,\n\x08response\x18\x01 \x01(\x0e\x32\x1a.StartJobResponse.Response\x12\x16\n\x04\x62ots\x18\x02 \x03(\x0b\x32\x08.BotData\"!\n\x08Response\x12\x0b\n\x07SUCCESS\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01\"y\n\x07\x42otData\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x1d\n\x05state\x18\x02 \x01(\x0e\x32\x0e.BotData.State\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\".\n\x05State\x12\x0b\n\x07OFFLINE\x10\x00\x12\x0b\n\x07WAITING\x10\x01\x12\x0b\n\x07WORKING\x10\x02\"\x1f\n\rGetJobRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\"\x84\x01\n\x03Job\x12\r\n\x05jobId\x18\x01 \x01(\x05\x12\x11\n\tcommandId\x18\x02 \x01(\x05\x12\x0e\n\x06userId\x18\x03 \x01(\t\x12\x19\n\x05state\x18\x04 \x01(\x0e\x32\n.Job.State\"0\n\x05State\x12\x0c\n\x08STARTING\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\x0c\n\x08\x46INISHED\x10\x02\" \n\x0eStopJobRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\"a\n\x0fStopJobResponse\x12+\n\x08response\x18\x01 \x01(\x0e\x32\x19.StopJobResponse.Response\"!\n\x08Response\x12\x0b\n\x07SUCCESS\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01\x32\x89\x01\n\x02\x43\x32\x12\x31\n\x08StartJob\x12\x10.StartJobRequest\x1a\x11.StartJobResponse\"\x00\x12 \n\x06GetJob\x12\x0e.GetJobRequest\x1a\x04.Job\"\x00\x12.\n\x07StopJob\x12\x0f.StopJobRequest\x1a\x10.StopJobResponse\"\x00\x62\x06proto3'
)



_STARTJOBRESPONSE_RESPONSE = _descriptor.EnumDescriptor(
  name='Response',
  full_name='StartJobResponse.Response',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAIL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=156,
  serialized_end=189,
)
_sym_db.RegisterEnumDescriptor(_STARTJOBRESPONSE_RESPONSE)

_BOTDATA_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='BotData.State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFFLINE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WAITING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WORKING', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=266,
  serialized_end=312,
)
_sym_db.RegisterEnumDescriptor(_BOTDATA_STATE)

_JOB_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='Job.State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STARTING', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FINISHED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=432,
  serialized_end=480,
)
_sym_db.RegisterEnumDescriptor(_JOB_STATE)

_STOPJOBRESPONSE_RESPONSE = _descriptor.EnumDescriptor(
  name='Response',
  full_name='StopJobResponse.Response',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAIL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=156,
  serialized_end=189,
)
_sym_db.RegisterEnumDescriptor(_STOPJOBRESPONSE_RESPONSE)


_STARTJOBREQUEST = _descriptor.Descriptor(
  name='StartJobRequest',
  full_name='StartJobRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='commandId', full_name='StartJobRequest.commandId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userId', full_name='StartJobRequest.userId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=12,
  serialized_end=64,
)


_STARTJOBRESPONSE = _descriptor.Descriptor(
  name='StartJobResponse',
  full_name='StartJobResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='StartJobResponse.response', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bots', full_name='StartJobResponse.bots', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STARTJOBRESPONSE_RESPONSE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=189,
)


_BOTDATA = _descriptor.Descriptor(
  name='BotData',
  full_name='BotData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='BotData.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='BotData.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='BotData.address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BOTDATA_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=312,
)


_GETJOBREQUEST = _descriptor.Descriptor(
  name='GetJobRequest',
  full_name='GetJobRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='GetJobRequest.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=345,
)


_JOB = _descriptor.Descriptor(
  name='Job',
  full_name='Job',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='jobId', full_name='Job.jobId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='commandId', full_name='Job.commandId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userId', full_name='Job.userId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='Job.state', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _JOB_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=480,
)


_STOPJOBREQUEST = _descriptor.Descriptor(
  name='StopJobRequest',
  full_name='StopJobRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='StopJobRequest.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=482,
  serialized_end=514,
)


_STOPJOBRESPONSE = _descriptor.Descriptor(
  name='StopJobResponse',
  full_name='StopJobResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='StopJobResponse.response', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STOPJOBRESPONSE_RESPONSE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=516,
  serialized_end=613,
)

_STARTJOBRESPONSE.fields_by_name['response'].enum_type = _STARTJOBRESPONSE_RESPONSE
_STARTJOBRESPONSE.fields_by_name['bots'].message_type = _BOTDATA
_STARTJOBRESPONSE_RESPONSE.containing_type = _STARTJOBRESPONSE
_BOTDATA.fields_by_name['state'].enum_type = _BOTDATA_STATE
_BOTDATA_STATE.containing_type = _BOTDATA
_JOB.fields_by_name['state'].enum_type = _JOB_STATE
_JOB_STATE.containing_type = _JOB
_STOPJOBRESPONSE.fields_by_name['response'].enum_type = _STOPJOBRESPONSE_RESPONSE
_STOPJOBRESPONSE_RESPONSE.containing_type = _STOPJOBRESPONSE
DESCRIPTOR.message_types_by_name['StartJobRequest'] = _STARTJOBREQUEST
DESCRIPTOR.message_types_by_name['StartJobResponse'] = _STARTJOBRESPONSE
DESCRIPTOR.message_types_by_name['BotData'] = _BOTDATA
DESCRIPTOR.message_types_by_name['GetJobRequest'] = _GETJOBREQUEST
DESCRIPTOR.message_types_by_name['Job'] = _JOB
DESCRIPTOR.message_types_by_name['StopJobRequest'] = _STOPJOBREQUEST
DESCRIPTOR.message_types_by_name['StopJobResponse'] = _STOPJOBRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartJobRequest = _reflection.GeneratedProtocolMessageType('StartJobRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTJOBREQUEST,
  '__module__' : 'c2_pb2'
  # @@protoc_insertion_point(class_scope:StartJobRequest)
  })
_sym_db.RegisterMessage(StartJobRequest)

StartJobResponse = _reflection.GeneratedProtocolMessageType('StartJobResponse', (_message.Message,), {
  'DESCRIPTOR' : _STARTJOBRESPONSE,
  '__module__' : 'c2_pb2'
  # @@protoc_insertion_point(class_scope:StartJobResponse)
  })
_sym_db.RegisterMessage(StartJobResponse)

BotData = _reflection.GeneratedProtocolMessageType('BotData', (_message.Message,), {
  'DESCRIPTOR' : _BOTDATA,
  '__module__' : 'c2_pb2'
  # @@protoc_insertion_point(class_scope:BotData)
  })
_sym_db.RegisterMessage(BotData)

GetJobRequest = _reflection.GeneratedProtocolMessageType('GetJobRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETJOBREQUEST,
  '__module__' : 'c2_pb2'
  # @@protoc_insertion_point(class_scope:GetJobRequest)
  })
_sym_db.RegisterMessage(GetJobRequest)

Job = _reflection.GeneratedProtocolMessageType('Job', (_message.Message,), {
  'DESCRIPTOR' : _JOB,
  '__module__' : 'c2_pb2'
  # @@protoc_insertion_point(class_scope:Job)
  })
_sym_db.RegisterMessage(Job)

StopJobRequest = _reflection.GeneratedProtocolMessageType('StopJobRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOPJOBREQUEST,
  '__module__' : 'c2_pb2'
  # @@protoc_insertion_point(class_scope:StopJobRequest)
  })
_sym_db.RegisterMessage(StopJobRequest)

StopJobResponse = _reflection.GeneratedProtocolMessageType('StopJobResponse', (_message.Message,), {
  'DESCRIPTOR' : _STOPJOBRESPONSE,
  '__module__' : 'c2_pb2'
  # @@protoc_insertion_point(class_scope:StopJobResponse)
  })
_sym_db.RegisterMessage(StopJobResponse)



_C2 = _descriptor.ServiceDescriptor(
  name='C2',
  full_name='C2',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=616,
  serialized_end=753,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartJob',
    full_name='C2.StartJob',
    index=0,
    containing_service=None,
    input_type=_STARTJOBREQUEST,
    output_type=_STARTJOBRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetJob',
    full_name='C2.GetJob',
    index=1,
    containing_service=None,
    input_type=_GETJOBREQUEST,
    output_type=_JOB,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StopJob',
    full_name='C2.StopJob',
    index=2,
    containing_service=None,
    input_type=_STOPJOBREQUEST,
    output_type=_STOPJOBRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_C2)

DESCRIPTOR.services_by_name['C2'] = _C2

# @@protoc_insertion_point(module_scope)
